blank_issues_enabled: false

# TODO: Redirect support questions
contact_links:
  - name: â“ Question
    url: https://github.com/vshn/appcat-cli/discussions
    about: Ask or discuss with us, we're happy to help ğŸ™‹
